name: build mvdsv
#on: [pull_request]
on: [push]
jobs:
  build:
#    if: github.repository == 'QW-Group/qwprot'
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
       target: [linux-amd64, linux-i686, linux-armhf, linux-aarch64]
       include:
         - target: linux-amd64
           os: linux
           arch: amd64
           ext: ".so"
         - target: linux-i686
           os: linux
           arch: i686
           ext: ".so"
         - target: linux-armhf
           os: linux
           arch: armhf
           ext: ".so"
         - target: linux-aarch64
           os: linux
           arch: aarch64
           ext: ".so"
    steps:
      - name: Checkout qwprot
        uses: actions/checkout@v3
      - name: Checkout mvdsv
        uses: actions/checkout@master
        with:
          repository: QW-Group/mvdsv
          path: ./mvdsv
          submodules: recursive
      - name: Prepare Build Environment
        run: |
             sudo apt-get update
             sudo apt-get -y install build-essential cmake gcc-i686-linux-gnu
             sudo apt-get -y install gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
             sudo apt-get -y install gcc-mingw-w64-x86-64 gcc-mingw-w64-i686
      - name: Update src/qwprot
        run: |
             cp src/* mvdsv/src/qwprot/
             head mvdsv/src/qwprot/src/protocol.h
             head src/protocol.h
      - name: Build mvdsv
        run: |
             cd mvdsv
             ./build_cmake.sh ${{ matrix.target }}
